import AppKit
import WindowPetCore

/// A short memory of what you have copied, so "what was that address again"
/// has an answer.
///
/// Held in memory only and never written to disk, and filtered twice before
/// anything is kept: once by the system, because password managers mark their
/// pasteboard entries concealed and those are skipped outright, and once by
/// ClipPolicy, which drops anything shaped like a key or a token. Rusty
/// already leaked a secret to a screenshot once in this project's history;
/// this is built so that cannot happen again through the clipboard.
@MainActor
final class ClipboardHistory {

    private(set) var clips: [String] = []
    private var lastChangeCount = NSPasteboard.general.changeCount
    private var ticker: DispatchSourceTimer?

    /// Types a password manager or a transient copier sets to say "do not
    /// keep this". Honouring them is the difference between a convenience and
    /// a liability.
    private static let concealedTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    var isEnabled: Bool {
        get {
            // On by default, because a clipboard history nobody switched on
            // is empty exactly when it is first needed.
            UserDefaults.standard.object(forKey: "clipboardHistory") == nil
                || UserDefaults.standard.bool(forKey: "clipboardHistory")
        }
        set {
            UserDefaults.standard.set(newValue, forKey: "clipboardHistory")
            if newValue { start() } else { stop(); clips.removeAll() }
        }
    }

    /// Starts recording as soon as anything touches the history, rather than
    /// waiting for a particular launch mode to remember to call start(). A
    /// background recorder that depends on wiring order is a recorder that is
    /// empty exactly when it is first needed.
    init() { start() }

    func start() {
        guard isEnabled, ticker == nil else { return }
        // Once a second. The pasteboard has no change notification, so polling
        // is the only way, and this is a single integer compare that only
        // reads the contents when that integer actually moved. Kept to 1 Hz
        // deliberately: the idle CPU budget in ENERGY.md is 0.3% of a core,
        // and this runs for the whole life of the app.
        let timer = DispatchSource.makeTimerSource(queue: .main)
        timer.schedule(deadline: .now() + 1, repeating: 1)
        timer.setEventHandler { [weak self] in self?.poll() }
        timer.resume()
        ticker = timer
    }

    func stop() {
        ticker?.cancel()
        ticker = nil
    }

    func clear() { clips.removeAll() }

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        let types = pasteboard.types ?? []
        guard !types.contains(where: { Self.concealedTypes.contains($0) }) else { return }
        guard let text = pasteboard.string(forType: .string) else { return }
        clips = ClipPolicy.insert(text, into: clips)
    }

    func listing() -> String { ClipPolicy.summary(clips) }

    /// Puts a remembered clip back on the clipboard. Copying it back bumps the
    /// change count, so the poll would re-record it; the history is rewritten
    /// deliberately instead, keeping the recalled clip at the front.
    func recall(_ query: String) -> (result: String, ok: Bool) {
        guard !clips.isEmpty else {
            return ("I have not recorded any clips yet.", false)
        }
        guard let index = ClipPolicy.match(query, in: clips) else {
            return ("I don't have a clip matching \(query).", false)
        }
        let clip = clips[index]
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(clip, forType: .string)
        lastChangeCount = pasteboard.changeCount
        clips = ClipPolicy.insert(clip, into: clips)
        let preview = clip.replacingOccurrences(of: "\n", with: " ")
        return ("Copied: \(preview.prefix(80))", true)
    }
}
