import AppKit

/// Loads the pet's animation frames (generated by PetGen, artist-swappable
/// PNG-for-PNG) plus a coarse alpha mask per frame for pixel hit-testing.
/// Frame swaps are plain CALayer contents changes — GPU-composited, near-free.
final class SpriteSet {

    enum Kind: String, CaseIterable {
        case idle, blink, walk, jump, fall, land, sleep, lookAround, fidget
    }

    /// One drawable frame: image + its hit mask.
    struct Frame {
        let image: CGImage
        let mask: AlphaMask
    }

    /// 32×32 boolean alpha grid — O(1) "is this pixel part of the creature"
    /// lookups for the click-through hole. ~1 KB per frame.
    struct AlphaMask {
        let side: Int
        let bits: [Bool] // row-major, row 0 = TOP scanline (CGBitmapContext layout)

        /// Sample with normalized sprite coordinates, y-up (AppKit convention).
        func opaque(x01: CGFloat, y01up: CGFloat) -> Bool {
            guard x01 >= 0, x01 <= 1, y01up >= 0, y01up <= 1 else { return false }
            let gx = min(side - 1, max(0, Int(x01 * CGFloat(side))))
            let rowFromTop = min(side - 1, max(0, side - 1 - Int(y01up * CGFloat(side))))
            return bits[rowFromTop * side + gx]
        }

        static func build(from image: CGImage, side: Int = 32) -> AlphaMask {
            var buf = [UInt8](repeating: 0, count: side * side * 4)
            buf.withUnsafeMutableBytes { raw in
                if let ctx = CGContext(data: raw.baseAddress, width: side, height: side,
                                       bitsPerComponent: 8, bytesPerRow: side * 4,
                                       space: CGColorSpaceCreateDeviceRGB(),
                                       bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue) {
                    ctx.draw(image, in: CGRect(x: 0, y: 0, width: side, height: side))
                }
            }
            // RGBA — alpha is every 4th byte.
            let bits = (0..<(side * side)).map { buf[$0 * 4 + 3] > 25 }
            return AlphaMask(side: side, bits: bits)
        }
    }

    struct Anim {
        let frames: [Frame]
        let durations: [TimeInterval]
        let loops: Bool
    }

    private(set) var anims: [Kind: Anim] = [:]
    private(set) var loadedFrameCount = 0
    /// Classic Shimeji art faces left; ours faces right. The stage flips
    /// accordingly so walking never moonwalks.
    let facesLeft: Bool

    /// Imported character: provided anims, missing kinds fall back to idle.
    init(anims provided: [Kind: Anim], facesLeft: Bool) {
        self.facesLeft = facesLeft
        anims = provided
        if let idle = provided[.idle] {
            for kind in Kind.allCases where anims[kind] == nil {
                anims[kind] = Anim(frames: [idle.frames[0]], durations: [1], loops: false)
            }
        }
        loadedFrameCount = provided.values.reduce(0) { $0 + $1.frames.count }
    }

    init(skin: String = SkinTheme.currentID) {
        facesLeft = false
        func img(_ name: String) -> CGImage? {
            let full = name.replacingOccurrences(of: "pet_", with: "pet_\(skin)_")
            guard let url = Bundle.module.url(forResource: full, withExtension: "png"),
                  let ns = NSImage(contentsOf: url),
                  ns.size.width > 4 else { return nil }
            return ns.cgImage(forProposedRect: nil, context: nil, hints: nil)
        }
        func build(_ kind: Kind, _ names: [String], _ durations: [TimeInterval], loops: Bool) {
            let images = names.compactMap(img)
            guard images.count == names.count else { return } // missing art → fallback below
            anims[kind] = Anim(
                frames: images.map { Frame(image: $0, mask: AlphaMask.build(from: $0)) },
                durations: durations, loops: loops)
            loadedFrameCount += images.count
        }
        build(.idle, ["pet_idle_0", "pet_idle_1", "pet_idle_0", "pet_idle_2"],
              [0.55, 0.5, 0.55, 0.6], loops: true)
        build(.blink, ["pet_blink_0"], [0.13], loops: false)
        build(.walk, (0..<10).map { "pet_walk_\($0)" },
              Array(repeating: 0.07, count: 10), loops: true)
        build(.jump, ["pet_jump_0"], [0.4], loops: false)
        build(.fall, ["pet_fall_0", "pet_fall_1"], [0.11, 0.11], loops: true)
        build(.land, ["pet_land_0", "pet_land_1"], [0.10, 0.08], loops: false)
        build(.sleep, ["pet_sleep_0", "pet_sleep_1"], [1.15, 1.15], loops: true)
        build(.lookAround, ["pet_look_0", "pet_look_1", "pet_look_2"],
              [0.55, 0.6, 0.35], loops: false)
        build(.fidget, (0..<4).map { "pet_fidget_\($0)" },
              Array(repeating: 0.13, count: 4), loops: false)

        // Any missing animation falls back to a static placeholder — the app
        // must run (visibly wrong, not crashed) even with no art at all.
        if anims.count < Kind.allCases.count {
            let ph = Self.placeholder()
            let phFrame = Frame(image: ph, mask: AlphaMask.build(from: ph))
            for kind in Kind.allCases where anims[kind] == nil {
                anims[kind] = Anim(frames: [phFrame], durations: [1], loops: false)
            }
        }
    }

    private static func placeholder() -> CGImage {
        let img = NSImage(size: NSSize(width: 64, height: 64))
        img.lockFocus()
        NSColor.systemOrange.withAlphaComponent(0.9).setFill()
        NSBezierPath(roundedRect: CGRect(x: 6, y: 6, width: 52, height: 52),
                     xRadius: 14, yRadius: 14).fill()
        img.unlockFocus()
        return img.cgImage(forProposedRect: nil, context: nil, hints: nil)!
    }
}

/// Advances an animation's frames against a timestamp. Driven by whatever
/// clock is currently running (display link while moving, slow ambient timer
/// while perched) — it has no timer of its own.
final class AnimationClock {
    private var anim: SpriteSet.Anim?
    private(set) var currentKind: SpriteSet.Kind?
    var currentKindName: String { currentKind?.rawValue ?? "none" }
    private var idx = 0
    private var nextAt: TimeInterval = 0
    private(set) var finished = true

    /// Forget the current animation so the next play() starts fresh — used
    /// when the sprite SET itself changes (character swap).
    func reset() {
        anim = nil
        currentKind = nil
        finished = true
    }

    @discardableResult
    func play(_ kind: SpriteSet.Kind, from set: SpriteSet, at now: TimeInterval) -> SpriteSet.Frame? {
        if kind == currentKind && !finished { return nil }
        guard let a = set.anims[kind] else { return nil }
        anim = a
        currentKind = kind
        idx = 0
        finished = false
        nextAt = now + a.durations[0]
        return a.frames[0]
    }

    func tick(at now: TimeInterval) -> SpriteSet.Frame? {
        guard let a = anim, !finished, now >= nextAt else { return nil }
        if idx + 1 < a.frames.count {
            idx += 1
        } else if a.loops {
            idx = 0
        } else {
            finished = true
            return nil
        }
        nextAt = now + a.durations[idx]
        return a.frames[idx]
    }
}
